In [3]:
import numpy as np

A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
# sum vertically
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [12]:
# take a 3x4 matrix divide by 1x4 matrix, call reshape to make sure the dimension
percentage = 100*A / cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [14]:
B = np.array([
    [1, 2, 3, 4]
])
# automatically copy 100 4 times into a 4x1 matrix
B.T + 100

array([[101],
       [102],
       [103],
       [104]])

In [15]:
# (m,n) matrix
C = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# (1,n) matrix
D = np.array([
    [100, 200, 300]
])

# It will take the (1,n) matrix copy m times, then add them up
C + D

array([[101, 202, 303],
       [104, 205, 306]])

In [16]:
# (m,1) matrix
E = np.array([
    [100],
    [200]
])

# It will take the (m,1) matrix copy n times, then add them up
C + E

array([[101, 102, 103],
       [204, 205, 206]])

In [17]:
a = np.random.randn(5)
print(a)

[-2.07384023 -0.26862655  2.26667971 -0.13077627 -0.57551958]


In [18]:
# rank 1 array, neither a row vector or column vector
# Don't use this one
print(a.shape)

(5,)


In [19]:
print(a.T)

[-2.07384023 -0.26862655  2.26667971 -0.13077627 -0.57551958]


In [20]:
print(np.dot(a, a.T))

9.859135653833807


In [21]:
a = np.random.randn(5,1)
print(a)

[[-0.95294955]
 [ 1.09283553]
 [-1.31502227]
 [ 2.32014486]
 [-0.17822014]]


In [22]:
print(a.T)

[[-0.95294955  1.09283553 -1.31502227  2.32014486 -0.17822014]]


In [23]:
print(np.dot(a, a.T))

[[ 0.90811285 -1.04141713  1.25314988 -2.21098101  0.1698348 ]
 [-1.04141713  1.19428949 -1.43710305  2.53553674 -0.1947653 ]
 [ 1.25314988 -1.43710305  1.72928356 -3.05104216  0.23436345]
 [-2.21098101  2.53553674 -3.05104216  5.38307219 -0.41349654]
 [ 0.1698348  -0.1947653   0.23436345 -0.41349654  0.03176242]]


In [24]:
# make sure the shape is (5,1)
assert(a.shape == (5,1))